version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "2222:22" # ホストのポート 2222 をコンテナのポート 22 にマッピング
      - "8086:8086"
      - "5000:5000"
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: team6
      POSTGRES_DB: team6db
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: